### ISSUE TITLE
time.Time conversion generates boilergql.TimeTimeToTime()

### ISSUE THREAD

**Issue by troian** [web-ridge/utils-go#7]
```go
		ID:        m.ID,
		StartsAt:  boilergql.TimeTimeToTime(m.StartsAt),
		EndsAt:    boilergql.TimeTimeToTime(m.EndsAt),
```

expected
```go
		ID:        m.ID,
		StartsAt:  m.StartsAt,
		EndsAt:    m.EndsAt,
```

**Comment by RichardLindhout** [comment]
Are both times exactly the same type?

**Comment by RichardLindhout** [comment]
Based on TimeTimeToTime they are

**Comment by RichardLindhout** [comment]
Strange, looking into it!

**Comment by troian** [comment]
Yah, types are equal

**Comment by RichardLindhout** [comment]
It should skip these as custom convert since type should be the same here
https://github.com/web-ridge/gqlgen-sqlboiler/blob/master/convert.go#L814

Just to be sure I did not know gqglen supported go timestamps when will they be generated?

**Comment by RichardLindhout** [comment]
So I can test if it's fixed. It generates as Int for me a.t.m. maybe we should change in sqlboiler-graphql-schema too.

**Comment by troian** [comment]
Thats what I have in gqlgen.yml
```
models:
  GeoPoint:
    model:
      - github.com/web-ridge/utils-go/boilergql.GeoPoint
  DateTime:
    model:
      - github.com/99designs/gqlgen/graphql.Time
```

and graphql.schema uses them like
```
scalar GeoPoint
scalar DateTime

type Type {
    startsAt: DateTime
    endsAt: DateTime
    createdAt: DateTime
    updatedAt: DateTime
}

```
